name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Retrieve required files
      run: wget https://drive.usercontent.google.com/download?id=1q4wA2GaeALgVH4e-lgyos0MA6nWNRWRk&export=download&authuser=0
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tpp
      
    - name: Run the Docker image
      run: docker run --rm --mount type=bind,source="$(pwd)",destination=/tpp tpp make -j
